"""Initial migration with event settings

Revision ID: 4256e4236016
Revises: 
Create Date: 2025-02-20 18:25:52.938916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4256e4236016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('airport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('from_station', sa.JSON(), nullable=False),
    sa.Column('to_station', sa.JSON(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('classes', sa.JSON(), nullable=False),
    sa.Column('pantry', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('host_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_coordinates', sa.JSON(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('price_tiers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('meta_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('allow_refunds', sa.Boolean(), nullable=True),
    sa.Column('show_remaining_tickets', sa.Boolean(), nullable=True),
    sa.Column('enable_waitlist', sa.Boolean(), nullable=True),
    sa.Column('booking_deadline', sa.Integer(), nullable=True),
    sa.Column('ticket_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('cabin_classes', sa.JSON(), nullable=False),
    sa.Column('baggage_allowance', sa.JSON(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], ),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number')
    )
    op.create_table('train_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=10), nullable=False),
    sa.Column('pnr', sa.String(length=10), nullable=False),
    sa.Column('travel_class', sa.String(length=5), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('journey_date', sa.DateTime(), nullable=False),
    sa.Column('num_passengers', sa.Integer(), nullable=False),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('passengers', sa.JSON(), nullable=False),
    sa.Column('seat_numbers', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('cancellation_time', sa.DateTime(), nullable=True),
    sa.Column('refund_status', sa.String(length=20), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnr')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('num_tickets', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('pnr', sa.String(length=6), nullable=False),
    sa.Column('travel_class', sa.String(length=20), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('journey_date', sa.DateTime(), nullable=False),
    sa.Column('num_passengers', sa.Integer(), nullable=False),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('passengers', sa.JSON(), nullable=False),
    sa.Column('seats', sa.JSON(), nullable=True),
    sa.Column('meal_preferences', sa.JSON(), nullable=True),
    sa.Column('special_requests', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('cancellation_time', sa.DateTime(), nullable=True),
    sa.Column('refund_status', sa.String(length=20), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('check_in_status', sa.Boolean(), nullable=True),
    sa.Column('boarding_pass_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_booking')
    op.drop_table('booking')
    op.drop_table('train_booking')
    op.drop_table('flight')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('train')
    op.drop_table('station')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
