"""add tier_id to booking model

Revision ID: 843d80fdd8f0
Revises: 4256e4236016
Create Date: 2025-02-20 18:43:07.836522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843d80fdd8f0'
down_revision = '4256e4236016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('tier_id')

    with op.batch_alter_table('airport', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
